stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  script:
    - echo "Skip, chưa có unit test"
  tags:
    - runner-builder
  only:
    - release/staging

build_job:
  stage: build
  before_script:
    - check=$(echo "$CI_COMMIT_MESSAGE" | sed -nE 's/^.*(\[tag\]staging).*$/\1/p')
    - |
      if [ "$check" != "[tag]staging" ]; then
        echo "Commit message does not contain [tag]staging → skip pipeline"
        exit 0
      fi
  script:
    - bash cicd/build.sh
  tags:
    - runner-builder
  only:
    - release/staging

deploy_job:
  stage: deploy
  before_script:
    - check=$(echo "$CI_COMMIT_MESSAGE" | sed -nE 's/^.*(\[tag\]staging).*$/\1/p')
    - |
      if [ "$check" != "[tag]staging" ]; then
        echo "Commit message does not contain [tag]staging → skip pipeline"
        exit 0
      fi
  script:
    - bash cicd/deploy.sh
    - bash cicd/clean.sh
  tags:
    - runner-stg-202
  only:
    - release/staging