services:
   app:
    container_name: ${ENVIRONMENT_NAME}-${PROJECT_NAME}
    image: ${APP_IMAGE}
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    environment:
      - NODE_ENV=staging
    ports:
      - "${PORT_APP}:3000"
    networks:
      - meu-solutions-staging

networks:
  meu-solutions-staging:
    external: true
    name: meu-solutions-staging