/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10PropertyId200,
  GetApiV10PropertyId200,
  GetApiV10PropertyParams,
  PostApiV10Property200,
  PropertyMutate,
  PutApiV10PropertyId200,
  ResponseGetAllData
} from '../models';

import { mainInstance } from '../mutator/custom-instance';





/**
 * Retrieve a single property record by its ID
 * @summary Get property by ID
 */
export const getApiV10PropertyId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return mainInstance<GetApiV10PropertyId200>(
      {url: `/api/v1.0/property/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV10PropertyIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/property/${id}`
    ] as const;
    }

export const getGetApiV10PropertyIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/property/${id}`
    ] as const;
    }

    
export const getGetApiV10PropertyIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PropertyId>>>, TError = void>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PropertyIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PropertyId>>> = ({ signal }) => getApiV10PropertyId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PropertyIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PropertyId>>>
export type GetApiV10PropertyIdInfiniteQueryError = void


export function useGetApiV10PropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PropertyId>>>, TError = void>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PropertyId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PropertyId>>>, TError = void>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PropertyId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PropertyId>>>, TError = void>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get property by ID
 */

export function useGetApiV10PropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PropertyId>>>, TError = void>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PropertyIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiV10PropertyIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10PropertyId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PropertyIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PropertyId>>> = ({ signal }) => getApiV10PropertyId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PropertyIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PropertyId>>>
export type GetApiV10PropertyIdQueryError = void


export function useGetApiV10PropertyId<TData = Awaited<ReturnType<typeof getApiV10PropertyId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PropertyId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PropertyId<TData = Awaited<ReturnType<typeof getApiV10PropertyId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PropertyId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PropertyId<TData = Awaited<ReturnType<typeof getApiV10PropertyId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get property by ID
 */

export function useGetApiV10PropertyId<TData = Awaited<ReturnType<typeof getApiV10PropertyId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PropertyId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PropertyIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update a single property record by its ID
 * @summary Update property by ID
 */
export const putApiV10PropertyId = (
    id: string,
    propertyMutate: PropertyMutate,
 ) => {
      
      
      return mainInstance<PutApiV10PropertyId200>(
      {url: `/api/v1.0/property/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: propertyMutate
    },
      );
    }
  


export const getPutApiV10PropertyIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10PropertyId>>, TError,{id: string;data: PropertyMutate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10PropertyId>>, TError,{id: string;data: PropertyMutate}, TContext> => {

const mutationKey = ['putApiV10PropertyId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10PropertyId>>, {id: string;data: PropertyMutate}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10PropertyId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10PropertyIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10PropertyId>>>
    export type PutApiV10PropertyIdMutationBody = PropertyMutate
    export type PutApiV10PropertyIdMutationError = void

    /**
 * @summary Update property by ID
 */
export const usePutApiV10PropertyId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10PropertyId>>, TError,{id: string;data: PropertyMutate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10PropertyId>>,
        TError,
        {id: string;data: PropertyMutate},
        TContext
      > => {

      const mutationOptions = getPutApiV10PropertyIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single property record by its ID
 * @summary Delete property by ID
 */
export const deleteApiV10PropertyId = (
    id: string,
 ) => {
      
      
      return mainInstance<DeleteApiV10PropertyId200>(
      {url: `/api/v1.0/property/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV10PropertyIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PropertyId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PropertyId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10PropertyId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10PropertyId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10PropertyId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10PropertyIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10PropertyId>>>
    
    export type DeleteApiV10PropertyIdMutationError = void

    /**
 * @summary Delete property by ID
 */
export const useDeleteApiV10PropertyId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PropertyId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10PropertyId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10PropertyIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of property with pagination, filtering and sorting
 * @summary Get all property
 */
export const getApiV10Property = (
    params?: GetApiV10PropertyParams,
 signal?: AbortSignal
) => {
      
      
      return mainInstance<ResponseGetAllData>(
      {url: `/api/v1.0/property`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV10PropertyInfiniteQueryKey = (params?: GetApiV10PropertyParams,) => {
    return [
    'infinite', `/api/v1.0/property`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10PropertyQueryKey = (params?: GetApiV10PropertyParams,) => {
    return [
    `/api/v1.0/property`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10PropertyInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Property>>>, TError = unknown>(params?: GetApiV10PropertyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PropertyInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Property>>> = ({ signal }) => getApiV10Property(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PropertyInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Property>>>
export type GetApiV10PropertyInfiniteQueryError = unknown


export function useGetApiV10PropertyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Property>>>, TError = unknown>(
 params: undefined |  GetApiV10PropertyParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Property>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Property>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PropertyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Property>>>, TError = unknown>(
 params?: GetApiV10PropertyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Property>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Property>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PropertyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Property>>>, TError = unknown>(
 params?: GetApiV10PropertyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all property
 */

export function useGetApiV10PropertyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Property>>>, TError = unknown>(
 params?: GetApiV10PropertyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PropertyInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiV10PropertyQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Property>>, TError = unknown>(params?: GetApiV10PropertyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PropertyQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Property>>> = ({ signal }) => getApiV10Property(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PropertyQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Property>>>
export type GetApiV10PropertyQueryError = unknown


export function useGetApiV10Property<TData = Awaited<ReturnType<typeof getApiV10Property>>, TError = unknown>(
 params: undefined |  GetApiV10PropertyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Property>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Property>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Property<TData = Awaited<ReturnType<typeof getApiV10Property>>, TError = unknown>(
 params?: GetApiV10PropertyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Property>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Property>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Property<TData = Awaited<ReturnType<typeof getApiV10Property>>, TError = unknown>(
 params?: GetApiV10PropertyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all property
 */

export function useGetApiV10Property<TData = Awaited<ReturnType<typeof getApiV10Property>>, TError = unknown>(
 params?: GetApiV10PropertyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Property>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PropertyQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new property record
 * @summary Create a property
 */
export const postApiV10Property = (
    propertyMutate: PropertyMutate,
 signal?: AbortSignal
) => {
      
      
      return mainInstance<PostApiV10Property200>(
      {url: `/api/v1.0/property`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: propertyMutate, signal
    },
      );
    }
  


export const getPostApiV10PropertyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Property>>, TError,{data: PropertyMutate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Property>>, TError,{data: PropertyMutate}, TContext> => {

const mutationKey = ['postApiV10Property'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Property>>, {data: PropertyMutate}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Property(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10PropertyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Property>>>
    export type PostApiV10PropertyMutationBody = PropertyMutate
    export type PostApiV10PropertyMutationError = unknown

    /**
 * @summary Create a property
 */
export const usePostApiV10Property = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Property>>, TError,{data: PropertyMutate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Property>>,
        TError,
        {data: PropertyMutate},
        TContext
      > => {

      const mutationOptions = getPostApiV10PropertyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    