/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface ActiveUser {
  id?: string;
  email?: string;
  username?: string;
  first_name?: string;
  last_name?: string;
  primary_role_name?: string;
  last_login_at?: string;
  created_at?: string;
}
