/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Appointment status
 * @nullable
 */
export type AppointmentStatus = typeof AppointmentStatus[keyof typeof AppointmentStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppointmentStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
