/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Appointment status
 */
export type AppointmentMutateStatus = typeof AppointmentMutateStatus[keyof typeof AppointmentMutateStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppointmentMutateStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
