/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { BadRequestResponseError } from './badRequestResponseError';
import type { BadRequestResponseResponseData } from './badRequestResponseResponseData';
import type { BadRequestResponseViolationItem } from './badRequestResponseViolationItem';

export type BadRequestResponse = {
  success?: boolean;
  error?: BadRequestResponseError;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  message_en?: string | null;
  /** @nullable */
  responseData?: BadRequestResponseResponseData;
  status?: string;
  timeStamp?: string;
  /** @nullable */
  violation?: BadRequestResponseViolationItem[] | null;
};
