/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface CandidateFile {
  /** Unique identifier */
  id?: string;
  /** Candidate ID */
  candidate_id?: string;
  /** File ID */
  file_id?: string;
  /**
   * Creation timestamp
   * @nullable
   */
  created_at?: string | null;
}
