/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface CandidateFileBulkMutate {
  /** Candidate ID */
  candidate_id: string;
  /** List of file IDs */
  file_ids: string[];
}
