/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryWithChildrenAllOfCategoriesItem } from './categoryWithChildrenAllOfCategoriesItem';

export type CategoryWithChildrenAllOf = {
  /** Nested child categories (recursive structure) */
  categories?: CategoryWithChildrenAllOfCategoriesItem[];
};
