/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface Contact {
  id?: string;
  name?: string;
  email?: string;
  phone_number?: string;
  content?: string;
  created_at?: string;
  type?: string;
}
