/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteApiV10FileId200AllOf } from './deleteApiV10FileId200AllOf';

export type DeleteApiV10FileId200 = ApiResponse & DeleteApiV10FileId200AllOf;
