/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteApiV10PageId200AllOf } from './deleteApiV10PageId200AllOf';

export type DeleteApiV10PageId200 = ApiResponse & DeleteApiV10PageId200AllOf;
