/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteApiV10UserId200AllOf } from './deleteApiV10UserId200AllOf';

export type DeleteApiV10UserId200 = ApiResponse & DeleteApiV10UserId200AllOf;
