/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { DeleteApiV10PermissionId200AllOf } from './deleteApiV10PermissionId200AllOf';

export type DeleteApiV10PermissionId200 = Response & DeleteApiV10PermissionId200AllOf;
