/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { DeleteApiV10RoleId200AllOf } from './deleteApiV10RoleId200AllOf';

export type DeleteApiV10RoleId200 = Response & DeleteApiV10RoleId200AllOf;
