/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Department status
 */
export type DepartmentMutateStatus = typeof DepartmentMutateStatus[keyof typeof DepartmentMutateStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DepartmentMutateStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
