/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Department status
 * @nullable
 */
export type DepartmentStatus = typeof DepartmentStatus[keyof typeof DepartmentStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DepartmentStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
