/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Information about compressed variants (for images)
 * @nullable
 */
export type FileCompressInfo = { [key: string]: unknown } | null;
