/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { FooterMutateLanguage } from './footerMutateLanguage';
import type { FooterMutateAddressItem } from './footerMutateAddressItem';
import type { FooterMutateSocialLinks } from './footerMutateSocialLinks';
import type { FooterMutateLinksItem } from './footerMutateLinksItem';
import type { FooterMutateInternalLinksItem } from './footerMutateInternalLinksItem';
import type { FooterMutateMemberBrandsItem } from './footerMutateMemberBrandsItem';
import type { FooterMutateTotalViews } from './footerMutateTotalViews';

export interface FooterMutate {
  /** Language of the footer */
  language: FooterMutateLanguage;
  /**
   * Footer description
   * @nullable
   */
  description?: string | null;
  /**
   * Footer sub description
   * @nullable
   */
  sub_description?: string | null;
  /**
   * Address information as array of locations
   * @nullable
   */
  address?: FooterMutateAddressItem[] | null;
  /**
   * Contact phone number (numbers, spaces, +, -, () allowed)
   * @nullable
   */
  phone?: string | null;
  /**
   * Contact email address
   * @nullable
   */
  email?: string | null;
  /**
   * Social media links in JSON format
   * @nullable
   */
  social_links?: FooterMutateSocialLinks;
  /**
   * Footer links in JSON array format
   * @nullable
   */
  links?: FooterMutateLinksItem[] | null;
  /**
   * Internal navigation links (e.g. About, News, Contact) for the footer menu
   * @nullable
   */
  internal_links?: FooterMutateInternalLinksItem[] | null;
  /**
   * Member brand entries for the Thương hiệu thành viên column (link and logo are optional)
   * @nullable
   */
  member_brands?: FooterMutateMemberBrandsItem[] | null;
  /**
   * Current number of online visitors
   * @minimum 0
   * @nullable
   */
  online_visitors?: number | null;
  /**
   * Total number of page views (can be number or numeric string)
   * @nullable
   */
  total_views?: FooterMutateTotalViews;
  /**
   * Whether the footer is active
   * @nullable
   */
  is_active?: boolean | null;
}
