/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Language of the footer
 */
export type FooterMutateLanguage = typeof FooterMutateLanguage[keyof typeof FooterMutateLanguage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FooterMutateLanguage = {
  vi: 'vi',
  en: 'en',
} as const;
