/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Total number of page views (can be number or numeric string)
 * @nullable
 */
export type FooterMutateTotalViews = number | string | null;
