/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10PropertyIdScope } from './getApiV10PropertyIdScope';

export type GetApiV10PropertyIdParams = {
scope?: GetApiV10PropertyIdScope;
};
