/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV10CategoryLanguage = typeof GetApiV10CategoryLanguage[keyof typeof GetApiV10CategoryLanguage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV10CategoryLanguage = {
  vi: 'vi',
  en: 'en',
} as const;
