/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10Province200AllOfResponseDataItem } from './getApiV10Province200AllOfResponseDataItem';

export type GetApiV10Province200AllOf = {
  responseData?: GetApiV10Province200AllOfResponseDataItem[];
};
