/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { GetApiV10PermissionId200AllOf } from './getApiV10PermissionId200AllOf';

export type GetApiV10PermissionId200 = Response & GetApiV10PermissionId200AllOf;
