/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from './post';

export type GetApiV10PostId200AllOf = {
  responseData?: Post;
};
