/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV10PropertyScope = typeof GetApiV10PropertyScope[keyof typeof GetApiV10PropertyScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV10PropertyScope = {
  ADMIN: 'ADMIN',
} as const;
