/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10AuthProfile200Data } from './getApiV10AuthProfile200Data';

export type GetApiV10AuthProfile200 = {
  success?: boolean;
  data?: GetApiV10AuthProfile200Data;
};
