/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV10AnalyticsActiveUsersParams = {
/**
 * Get all-time page views from 2020-01-01 to today (overrides startDate/endDate)
 */
allTime?: boolean;
/**
 * Start date for page views (default "30daysAgo")
 */
startDate?: string;
/**
 * End date for page views (default "today")
 */
endDate?: string;
};
