/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { GetApiV10DepartmentId200AllOf } from './getApiV10DepartmentId200AllOf';

export type GetApiV10DepartmentId200 = Response & GetApiV10DepartmentId200AllOf;
