/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10PropertyId200AllOf } from './getApiV10PropertyId200AllOf';

export type GetApiV10PropertyId200 = ApiResponse & GetApiV10PropertyId200AllOf;
