/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10AnalyticsActiveUsers200AllOfResponseDataDateRange } from './getApiV10AnalyticsActiveUsers200AllOfResponseDataDateRange';

export type GetApiV10AnalyticsActiveUsers200AllOfResponseData = {
  /** Number of currently active users */
  activeUsers?: number;
  /** Timestamp of active users data */
  timestamp?: string;
  /** Total page views in date range */
  totalPageViews?: number;
  dateRange?: GetApiV10AnalyticsActiveUsers200AllOfResponseDataDateRange;
};
