/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10AuthProfile200DataRole } from './getApiV10AuthProfile200DataRole';

export type GetApiV10AuthProfile200Data = {
  id?: string;
  email?: string;
  username?: string;
  role?: GetApiV10AuthProfile200DataRole;
  permissions?: string[];
};
