/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10AnalyticsActiveUsers200AllOfResponseData } from './getApiV10AnalyticsActiveUsers200AllOfResponseData';

export type GetApiV10AnalyticsActiveUsers200AllOf = {
  responseData?: GetApiV10AnalyticsActiveUsers200AllOfResponseData;
};
