/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10LogoId200AllOf } from './getApiV10LogoId200AllOf';

export type GetApiV10LogoId200 = ApiResponse & GetApiV10LogoId200AllOf;
