/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV10AuthProfile200DataRole = typeof GetApiV10AuthProfile200DataRole[keyof typeof GetApiV10AuthProfile200DataRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV10AuthProfile200DataRole = {
  user: 'user',
  admin: 'admin',
  system_admin: 'system_admin',
} as const;
