/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10CategoryLanguage } from './getApiV10CategoryLanguage';

export type GetApiV10CategoryParams = {
/**
 * Filter categories by language (vi or en)
 */
language?: GetApiV10CategoryLanguage;
};
