/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostCategory } from './postCategory';

export type GetApiV10PostCategoryId200AllOf = {
  responseData?: PostCategory;
};
