/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV10PropertyIdScope = typeof GetApiV10PropertyIdScope[keyof typeof GetApiV10PropertyIdScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV10PropertyIdScope = {
  ADMIN: 'ADMIN',
} as const;
