/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Role } from './role';

export type GetApiV10RoleId200AllOf = {
  responseData?: Role;
};
