/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PageConfig } from './pageConfig';

export type GetApiV10PageConfigId200AllOf = {
  responseData?: PageConfig;
};
