/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { GetApiV10Province200AllOf } from './getApiV10Province200AllOf';

export type GetApiV10Province200 = Response & GetApiV10Province200AllOf;
