/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export type GetApiV10UserId200AllOf = {
  responseData?: User;
};
