/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * API health status
 */
export type HealthCheckChecksApi = typeof HealthCheckChecksApi[keyof typeof HealthCheckChecksApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckChecksApi = {
  ok: 'ok',
  failed: 'failed',
} as const;
