/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Database connection status
 */
export type HealthCheckChecksDatabase = typeof HealthCheckChecksDatabase[keyof typeof HealthCheckChecksDatabase];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckChecksDatabase = {
  ok: 'ok',
  failed: 'failed',
} as const;
