/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Redis connection status
 */
export type HealthCheckChecksRedis = typeof HealthCheckChecksRedis[keyof typeof HealthCheckChecksRedis];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckChecksRedis = {
  ok: 'ok',
  failed: 'failed',
  skipped: 'skipped',
} as const;
