/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Overall health status
 */
export type HealthCheckStatus = typeof HealthCheckStatus[keyof typeof HealthCheckStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckStatus = {
  healthy: 'healthy',
  unhealthy: 'unhealthy',
} as const;
