/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { HealthCheckChecksApi } from './healthCheckChecksApi';
import type { HealthCheckChecksDatabase } from './healthCheckChecksDatabase';
import type { HealthCheckChecksRedis } from './healthCheckChecksRedis';

/**
 * Individual component checks
 */
export type HealthCheckChecks = {
  /** API health status */
  api?: HealthCheckChecksApi;
  /** Database connection status */
  database?: HealthCheckChecksDatabase;
  /** Redis connection status */
  redis?: HealthCheckChecksRedis;
};
