/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface LoginResponse {
  /** JWT access token */
  access_token: string;
  /** JWT refresh token */
  refresh_token: string;
  /** Access token expiration time in seconds */
  expires_in: number;
  /** Refresh token expiration time in seconds */
  refresh_expires_in: number;
  token_type: string;
}
