/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Device information for session tracking
 */
export type LoginRequestDeviceInfo = { [key: string]: unknown };
