/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { LoginRequestDeviceInfo } from './loginRequestDeviceInfo';

export interface LoginRequest {
  email: string;
  password: string;
  /** Device information for session tracking */
  device_info?: LoginRequestDeviceInfo;
  /** IP address for security logging */
  ip_address?: string;
  /** User agent string */
  user_agent?: string;
}
