/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface LogoMutate {
  name?: string;
  file_id?: string;
  navigation_link?: string;
  is_active?: boolean;
}
