/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface MonthlyTraffic {
  /** Month in YYYY-MM format */
  month?: string;
  /** Number of unique users */
  users?: number;
  /** Number of sessions */
  sessions?: number;
  /** Number of page views */
  pageViews?: number;
}
