/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Notification } from './notification';

export interface NotificationListData {
  count?: number;
  rows?: Notification[];
  page?: number;
  pageSize?: number;
  /** Total unread notifications of current user */
  unread_count?: number;
  /** True when current user still has unread notifications */
  has_unread?: boolean;
}
