/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface NotificationMutate {
  /**
   * Notification title
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /**
   * Notification content
   * @minLength 1
   */
  content: string;
  /**
   * Recipient user IDs
   * @minItems 1
   */
  belongs_to_user_id: string[];
  /**
   * Notification expiration time
   * @nullable
   */
  expired_at?: string | null;
}
