/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationChartSize } from './organizationChartSize';
import type { OrganizationChartCoordinates } from './organizationChartCoordinates';

export interface OrganizationChart {
  /** Unique identifier */
  id?: string;
  /**
   * Department ID
   * @nullable
   */
  department_id?: string | null;
  /**
   * Department name (resolved from department_id)
   * @nullable
   */
  department_name?: string | null;
  /** Full name */
  full_name?: string;
  /**
   * Position or title
   * @nullable
   */
  position?: string | null;
  /**
   * Node color
   * @nullable
   */
  color?: string | null;
  /**
   * Node size metadata
   * @nullable
   */
  size?: OrganizationChartSize;
  /**
   * Node coordinates
   * @nullable
   */
  coordinates?: OrganizationChartCoordinates;
  /**
   * Avatar URL
   * @nullable
   */
  avatar_url?: string | null;
  /**
   * Description
   * @nullable
   */
  description?: string | null;
}
