/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationChartMutateSize } from './organizationChartMutateSize';
import type { OrganizationChartMutateCoordinates } from './organizationChartMutateCoordinates';

export interface OrganizationChartMutate {
  /**
   * Full name
   * @minLength 1
   * @maxLength 255
   */
  full_name: string;
  /**
   * Position or title
   * @nullable
   */
  position?: string | null;
  /**
   * Node color
   * @nullable
   */
  color?: string | null;
  /**
   * Node size metadata
   * @nullable
   */
  size?: OrganizationChartMutateSize;
  /**
   * Node coordinates
   * @nullable
   */
  coordinates?: OrganizationChartMutateCoordinates;
  /**
   * Avatar URL
   * @nullable
   */
  avatar_url?: string | null;
  /**
   * Description
   * @nullable
   */
  description?: string | null;
  /**
   * Department ID
   * @nullable
   */
  department_id?: string | null;
}
