/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * page, visit https://www.npmjs.com/package/sequelize-api-paginate for syntax
 */
export type PageParameter = number;
