/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PasswordResetSubmit {
  /** User email address (must have verified OTP first) */
  email: string;
  /**
   * New password (min 8 chars, must contain uppercase, lowercase, number)
   * @minLength 8
   */
  newPassword: string;
  /** Confirm new password */
  confirmPassword: string;
}
