/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PasswordResetVerify {
  /** User email address */
  email: string;
  /**
   * 6-digit verification code
   * @pattern ^\d{6}$
   */
  code: string;
}
