/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PasswordResetCode {
  id?: string;
  user_id?: string;
  code?: string;
  expires_at?: string;
  is_used?: boolean;
  created_at?: string;
}
