/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10Property200AllOf } from './postApiV10Property200AllOf';

export type PostApiV10Property200 = ApiResponse & PostApiV10Property200AllOf;
