/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV10FileBulkBody = {
  files?: Blob[];
  /** Apply this value to `is_in_library` for all uploaded files (overrides per-file values) */
  is_in_library_all?: boolean;
};
