/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Action (APPROVED or REJECTED)
 */
export type PostApprovalHistoryAction = typeof PostApprovalHistoryAction[keyof typeof PostApprovalHistoryAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApprovalHistoryAction = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
