/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostContent } from './postContent';

export type PostWithContentAllOf = {
  post_content?: PostContent[];
  /** Array of Category IDs associated with the post */
  category_ids?: string[];
};
