/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV10AuthRefreshBodyDeviceInfo } from './postApiV10AuthRefreshBodyDeviceInfo';

export type PostApiV10AuthRefreshBody = {
  /** Refresh token (optional if sent via cookie) */
  refresh_token?: string;
  /** Device information */
  device_info?: PostApiV10AuthRefreshBodyDeviceInfo;
};
