/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10Service200AllOf } from './postApiV10Service200AllOf';

export type PostApiV10Service200 = ApiResponse & PostApiV10Service200AllOf;
