/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApprovalResultStatus } from './postApprovalResultStatus';

export interface PostApprovalResult {
  /** Approval result status */
  status: PostApprovalResultStatus;
  /**
   * Approval note
   * @nullable
   */
  note?: string | null;
}
