/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV10AuthForgotPasswordConfirmReset200AllOfResponseData } from './postApiV10AuthForgotPasswordConfirmReset200AllOfResponseData';

export type PostApiV10AuthForgotPasswordConfirmReset200AllOf = {
  responseData?: PostApiV10AuthForgotPasswordConfirmReset200AllOfResponseData;
};
