/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterResponse } from './registerResponse';
import type { PostApiV10AuthRegister200Message } from './postApiV10AuthRegister200Message';

export type PostApiV10AuthRegister200 = {
  success?: boolean;
  data?: RegisterResponse;
  message?: PostApiV10AuthRegister200Message;
};
