/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { PostApiV10CategoryBulk200AllOf } from './postApiV10CategoryBulk200AllOf';

export type PostApiV10CategoryBulk200 = Response & PostApiV10CategoryBulk200AllOf;
