/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { QuotationMutate } from './quotationMutate';
import type { PostApiV10QuotationBodyAllOf } from './postApiV10QuotationBodyAllOf';

export type PostApiV10QuotationBody = QuotationMutate & PostApiV10QuotationBodyAllOf;
