/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV10EmailSendQuotation200AllOfResponseData } from './postApiV10EmailSendQuotation200AllOfResponseData';

export type PostApiV10EmailSendQuotation200AllOf = {
  responseData?: PostApiV10EmailSendQuotation200AllOfResponseData;
};
