/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PostCategory {
  post_id?: string;
  category_id?: string;
  created_at?: string;
  page_id?: string;
  position?: number;
  id?: string;
}
