/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponse } from './loginResponse';
import type { PostApiV10AuthLogin200Message } from './postApiV10AuthLogin200Message';

export type PostApiV10AuthLogin200 = {
  success?: boolean;
  data?: LoginResponse;
  message?: PostApiV10AuthLogin200Message;
};
