/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from './post';
import type { PostWithContentAllOf } from './postWithContentAllOf';

export type PostWithContent = Post & PostWithContentAllOf;
