/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { PostApiV10RolePermissionRoleIdAssign200AllOf } from './postApiV10RolePermissionRoleIdAssign200AllOf';

export type PostApiV10RolePermissionRoleIdAssign200 = Response & PostApiV10RolePermissionRoleIdAssign200AllOf;
