/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Approval status
 * @nullable
 */
export type PostMutateStatus = typeof PostMutateStatus[keyof typeof PostMutateStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostMutateStatus = {
  DRAFT: 'DRAFT',
  PENDING_L1: 'PENDING_L1',
  PENDING_L2: 'PENDING_L2',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
} as const;
