/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Approval result status
 */
export type PostApprovalResultStatus = typeof PostApprovalResultStatus[keyof typeof PostApprovalResultStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApprovalResultStatus = {
  PENDING_L2: 'PENDING_L2',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
} as const;
