/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { PostApiV10UserRole200AllOf } from './postApiV10UserRole200AllOf';

export type PostApiV10UserRole200 = Response & PostApiV10UserRole200AllOf;
