/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { QuotationMutate } from './quotationMutate';
import type { PostApiV10QuotationPublicBodyAllOf } from './postApiV10QuotationPublicBodyAllOf';

export type PostApiV10QuotationPublicBody = QuotationMutate & PostApiV10QuotationPublicBodyAllOf;
