/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PostContentMutate {
  content?: string;
  position?: number;
  image_columns?: number;
  image_rows?: number;
  post_id?: string;
}
