/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV10AuthLogin423ErrorMessage } from './postApiV10AuthLogin423ErrorMessage';

export type PostApiV10AuthLogin423Error = {
  code?: string;
  message?: PostApiV10AuthLogin423ErrorMessage;
};
