/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV10AuthLogin423Error } from './postApiV10AuthLogin423Error';

export type PostApiV10AuthLogin423 = {
  success?: boolean;
  error?: PostApiV10AuthLogin423Error;
};
