/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV10AuthLogout200Message } from './postApiV10AuthLogout200Message';

export type PostApiV10AuthLogout200 = {
  success?: boolean;
  message?: PostApiV10AuthLogout200Message;
};
