/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10Appointment200AllOf } from './postApiV10Appointment200AllOf';

export type PostApiV10Appointment200 = ApiResponse & PostApiV10Appointment200AllOf;
