/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10ReceiveMethod200AllOf } from './postApiV10ReceiveMethod200AllOf';

export type PostApiV10ReceiveMethod200 = ApiResponse & PostApiV10ReceiveMethod200AllOf;
