/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PropertyMutateTransactionGroup } from './propertyMutateTransactionGroup';
import type { PropertyMutatePriceUnit } from './propertyMutatePriceUnit';
import type { PropertyMutateStatus } from './propertyMutateStatus';

export interface PropertyMutate {
  /**
   * Tên sản phẩm
   * @maxLength 255
   * @nullable
   */
  title?: string | null;
  /**
   * Nhóm giao dịch
   * @nullable
   */
  transaction_group?: PropertyMutateTransactionGroup;
  /**
   * Vị trí
   * @maxLength 500
   * @nullable
   */
  location?: string | null;
  /**
   * Kiến trúc và tiện ích
   * @nullable
   */
  architecture?: string | null;
  price_unit?: PropertyMutatePriceUnit;
  status?: PropertyMutateStatus;
  /** @maxItems 20 */
  media_file_ids?: string[];
  /**
   * Mô tả bất động sản
   * @nullable
   */
  description?: string | null;
  /**
   * Thể loại bất động sản
   * @maxLength 100
   * @nullable
   */
  category?: string | null;
  /**
   * Hướng nhà
   * @maxLength 50
   * @nullable
   */
  direction?: string | null;
  /**
   * Số tầng
   * @minimum 0
   * @nullable
   */
  floors?: number | null;
  /**
   * Số toilet
   * @minimum 0
   * @nullable
   */
  toilets?: number | null;
  /**
   * Mặt tiền đường
   * @maxLength 100
   * @nullable
   */
  street_frontage?: string | null;
  /**
   * Số phòng khách
   * @minimum 0
   * @nullable
   */
  living_rooms?: number | null;
  /**
   * Số phòng ngủ
   * @minimum 0
   * @nullable
   */
  bedrooms?: number | null;
  /**
   * Pháp lý
   * @maxLength 255
   * @nullable
   */
  legal?: string | null;
  /**
   * File ID liên kết
   * @nullable
   */
  file_id?: string | null;
  /**
   * Phân tích bất động sản
   * @nullable
   */
  analysis?: string | null;
  /**
   * Giá bất động sản
   * @minimum 0
   * @nullable
   */
  price?: number | null;
  /**
   * Số điện thoại nhân viên bán hàng
   * @maxLength 20
   * @nullable
   */
  phone_sale?: string | null;
}
