/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PropertyInquiryKind } from './propertyInquiryKind';

export interface PropertyInquiry {
  /** @maxLength 255 */
  name: string;
  /**
   * @minLength 8
   * @maxLength 20
   */
  phone_number: string;
  /** @maxLength 5000 */
  content?: string;
  kind: PropertyInquiryKind;
}
