/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PropertyMutatePriceUnit = typeof PropertyMutatePriceUnit[keyof typeof PropertyMutatePriceUnit];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyMutatePriceUnit = {
  VND: 'VND',
  VND_MONTH: 'VND_MONTH',
  VND_M2: 'VND_M2',
  VND_M2_MONTH: 'VND_M2_MONTH',
  USD: 'USD',
  USD_MONTH: 'USD_MONTH',
  USD_M2: 'USD_M2',
  USD_M2_MONTH: 'USD_M2_MONTH',
} as const;
