/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Nhóm giao dịch
 * @nullable
 */
export type PropertyMutateTransactionGroup = typeof PropertyMutateTransactionGroup[keyof typeof PropertyMutateTransactionGroup] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyMutateTransactionGroup = {
  SALE: 'SALE',
  RENT: 'RENT',
  DISTRIBUTION: 'DISTRIBUTION',
  INVESTMENT: 'INVESTMENT',
  MA: 'MA',
} as const;
