/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10FooterId200AllOf } from './putApiV10FooterId200AllOf';

export type PutApiV10FooterId200 = ApiResponse & PutApiV10FooterId200AllOf;
