/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Page } from './page';

export type PutApiV10PageId200AllOf = {
  responseData?: Page;
};
