/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV10UserIdResetPassword200AllOfResponseData } from './putApiV10UserIdResetPassword200AllOfResponseData';

export type PutApiV10UserIdResetPassword200AllOf = {
  responseData?: PutApiV10UserIdResetPassword200AllOfResponseData;
};
