/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10FileId200AllOf } from './putApiV10FileId200AllOf';

export type PutApiV10FileId200 = ApiResponse & PutApiV10FileId200AllOf;
