/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { QuotationPut } from './quotationPut';
import type { PutApiV10QuotationIdBodyAllOf } from './putApiV10QuotationIdBodyAllOf';

export type PutApiV10QuotationIdBody = QuotationPut & PutApiV10QuotationIdBodyAllOf;
