/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { PutApiV10RoleId200AllOf } from './putApiV10RoleId200AllOf';

export type PutApiV10RoleId200 = Response & PutApiV10RoleId200AllOf;
