/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10PageConfigId200AllOf } from './putApiV10PageConfigId200AllOf';

export type PutApiV10PageConfigId200 = ApiResponse & PutApiV10PageConfigId200AllOf;
