/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10CalibrationId200AllOf } from './putApiV10CalibrationId200AllOf';

export type PutApiV10CalibrationId200 = ApiResponse & PutApiV10CalibrationId200AllOf;
