/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Service } from './service';

export type PutApiV10ServiceId200AllOf = {
  responseData?: Service;
};
