/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10PostId200AllOf } from './putApiV10PostId200AllOf';

export type PutApiV10PostId200 = ApiResponse & PutApiV10PostId200AllOf;
