/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface QuotationFile {
  id?: string;
  file_id?: string;
  quotation_id?: string;
  created_at?: string;
}
