/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseResponseData } from './responseResponseData';
import type { ResponseViolationItem } from './responseViolationItem';

export interface Response {
  message?: string;
  message_en?: string;
  responseData?: ResponseResponseData;
  status?: string;
  timeStamp?: string;
  violation?: ResponseViolationItem[];
}
