/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface RoleMutate {
  /**
   * Name of the role
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Description of the role
   * @nullable
   */
  description?: string | null;
}
