/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface Role {
  /** Unique identifier of the role */
  id?: string;
  /** Name of the role */
  name?: string;
  /**
   * Description of the role
   * @nullable
   */
  description?: string | null;
  /**
   * Creation timestamp
   * @nullable
   */
  created_at?: string | null;
  /**
   * Last update timestamp
   * @nullable
   */
  updated_at?: string | null;
  /**
   * ID of the user who created this role
   * @nullable
   */
  created_by?: string | null;
  /**
   * ID of the user who last updated this role
   * @nullable
   */
  updated_by?: string | null;
}
