/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface RolePermission {
  /** Unique identifier */
  id?: string;
  /** Role ID */
  role_id?: string;
  /** Permission ID */
  permission_id?: string;
  /** Creation timestamp */
  created_at?: string;
}
