/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UserSessionsDetailedMutateDeviceInfo } from './userSessionsDetailedMutateDeviceInfo';

export interface UserSessionsDetailedMutate {
  user_id?: string;
  session_token?: string;
  refresh_token?: string;
  token_version?: number;
  device_info?: UserSessionsDetailedMutateDeviceInfo;
  ip_address?: string;
  user_agent?: string;
  expires_at?: string;
  refresh_expires_at?: string;
  is_active?: boolean;
  last_activity_at?: string;
  email?: string;
  username?: string;
  first_name?: string;
  last_name?: string;
}
