/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface UserRoleMutate {
  /** User ID */
  user_id: string;
  /** Role ID */
  role_id: string;
  /** Whether this is the user's primary role */
  is_primary?: boolean;
}
