/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface UserDepartmentMutate {
  /** User ID */
  user_id: string;
  /** Department ID */
  department_id: string;
}
