/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface WorkScheduleMutate {
  /**
   * Work schedule title
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /**
   * Work schedule description
   * @nullable
   */
  description?: string | null;
  /**
   * Tasks in this work schedule
   * @nullable
   */
  tasks?: string | null;
  /**
   * Free-text name of the host
   * @nullable
   */
  host?: string | null;
  /**
   * Free-text list of participants
   * @nullable
   */
  participants?: string | null;
  /** Work schedule date-time */
  schedule_time: string;
  /**
   * Work schedule end time
   * @nullable
   */
  end_time?: string | null;
  /**
   * Status of work schedule
   * @maxLength 50
   */
  status?: string;
}
